version: "3.8"
services:
  dbapp:
    build: ./dbapp
    container_name: cntdbapp
    ports:
      - "8001:8001"
  webapp:
    build: ./webapp
    container_name: cntwebapp
    ports:
      - "8000:8000"
    depends_on:
      - dbapp